import { Controller, Get, Param, Post } from '@nestjs/common';
import type { User } from '@prisma/client';
import { CurrentUser } from '../auth/decorators/current-user.decorator';
import { CertificatesService } from './certificates.service';

// Authenticated, but deliberately NOT gated by EventRoleGuard — a
// certificate can be generated by any eligible participant or judge on
// this event, not just organizers, and eligibility itself is a
// participation/judging-record question VotingService-style resolved
// inside the service, not an EventMembership role check (Section 2.2,
// docs/stages/12-certificates.md). SessionAuthGuard (global) already
// requires a logged-in user before either route is reached — there is
// no anonymous certificate-generation path, by construction (Section 2:
// the recipient is always the authenticated caller).
@Controller('events/:eventId/certificates')
export class CertificateSelfController {
  constructor(private readonly certificates: CertificatesService) {}

  @Post('mine')
  generateMine(@Param('eventId') eventId: string, @CurrentUser() user: User) {
    return this.certificates.generateMine(eventId, user.id);
  }

  @Get('mine')
  listMine(@Param('eventId') eventId: string, @CurrentUser() user: User) {
    return this.certificates.listMine(eventId, user.id);
  }
}
